points_to_evaluate:
  - hparams.optimizer.lr: 0.01
    hparams.optimizer.weight_decay: 5e-4
    hparams.lambda_cls: 1.0
    hparams.lambda_metric: 1.0
    hparams.lambda_adloss: 0.5
search_space:
  hparams.optimizer.lr:
    type: ray.tune.loguniform
    lower: 1.0e-6
    upper: 1.0e-3
  hparams.optimizer.weight_decay:
    type: ray.tune.loguniform
    lower: 1.0e-6
    upper: 1.0e-3
  hparams.lambda_cls:
    type: ray.tune.uniform
    lower: 0.1
    upper: 1.0
  hparams.lambda_metric:
    type: ray.tune.uniform
    lower: 0.1
    upper: 2.0
  hparams.lambda_adloss:
    type: ray.tune.uniform
    lower: 0.0
    upper: 1.0
algo:
  type: ray.tune.suggest.hyperopt.HyperOptSearch
scheduler:
  type: ray.tune.schedulers.MedianStoppingRule
  time_attr: training_iteration
  grace_period: 3
max_concurrent: 1
init_kwargs:
  num_cpus: 4
  num_gpus: 1
run_kwargs:
  metric: casia_mfsd_test_EER
  mode: min
  resources_per_trial:
    cpu: 4
    gpu: 1
  num_samples: 1
  verbose: 0
