amp:
  enabled: true
use_cpu: false
benchmark: false
data_parallel: false
deterministic: true
log_every_n_step: 10
num_workers: 4
mlflow_tracking_username: verihubs-vision
mlflow_tracking_password: Zjg3NDIwZTM1ZjdmNTU3NWJjMWM4Mjk5
mlflow_tracking_uri: http://127.0.0.1:8002/
mlflow_experiment_name: skripsi-4
mlflow_tags:
  developer: goldius
  repoName: fas-simple-distill
  Backup_Artifacts: true

hparams:
  seed: 666
  iter_per_epoch: 10
  max_iter: 4000
  max_epoch: 400
  num_live_domains: 3
  model:
    type: fas_simple_distill.model.resnet_ssdg.ssdg_resnet_baseline_no_relu.DG_model
    model: resnet18
    embedding_size: 512
    drop_rate: 0.5
    pretrained_path: "/mnt/data/skripsi_4_playground/goldius/FAS-Skripsi-4/fas_simple_distill/weights/resnet18-5c106cde.pth"
    norm_flag: true
    detach_classifier: false
  fr_model:
    type: fas_simple_distill.model.resnet_ssdg.ssdg_resnet_baseline_fr_confusion_cosface.FeatureEmbedderiResNetTorch
    model_type: r18
    pretrained_path: "/mnt/data/skripsi_4_playground/goldius/FAS-Skripsi-4/fas_simple_distill/weights/cosface_iresnet18.pth"
    norm_flag: true
  discriminator:
    type: fas_simple_distill.model.resnet_ssdg.ssdg_resnet_baseline_no_relu.Discriminator
    num_classes: 3
    max_iter: 4000
    in_features: 512
  criterion_cls:
    type: torch.nn.CrossEntropyLoss
    label_smoothing: 0.0
  criterion_dom:
    type: torch.nn.CrossEntropyLoss
    label_smoothing: 0.0
  optimizer:
    type: torch.optim.SGD
    lr: 0.01
    weight_decay: 5e-4
    momentum: 0.9
  init_lr: 0.01
  lr_epoch_1: 0
  lr_epoch_2: 400
  HardTripletLoss:
    type: fas_simple_distill.ops.ssdg.HardTripletLoss
    margin: 0.5
    hardest: false
    # type: pytorch_metric_learning.losses.contrastive_loss.ContrastiveLoss
    # pos_margin: 0
    # neg_margin: 1
  batch_size: 60
  lambda_cls: 1.0
  lambda_metric: 1.0
  lambda_adloss: 0.5
  lambda_mining: 1.0
  metric_loss:
    loss_type: HardTripletLoss

dataset:
  train_dataset:
    disable_blank_mitigation: true
    align_config:
      scale: 0.75
      crop_size: 256 
      select_method: AREA
      no_face_handling: skip
    use_custom_domain_label: True
    urls:
      - dom_lbl: 0
        name: "oulu_npu_live"
        url: [
          "/mnt/data/datasets/fas/skripsi_4_datasets/1_frame/oulu_npu/train/live/oulu_npu-train-live-{0000..0035}.tar",
          "/mnt/data/datasets/fas/skripsi_4_datasets/1_frame/oulu_npu/dev/live/oulu_npu-dev-live-{0000..0026}.tar",
          "/mnt/data/datasets/fas/skripsi_4_datasets/1_frame/oulu_npu/test/live/oulu_npu-test-live-{0000..0035}.tar",
        ]
      - dom_lbl: 1
        name: "oulu_npu_spoof"
        url: [
          "/mnt/data/datasets/fas/skripsi_4_datasets/1_frame/oulu_npu/train/spoof/oulu_npu-train-spoof-{0000..0143}.tar",
          "/mnt/data/datasets/fas/skripsi_4_datasets/1_frame/oulu_npu/dev/spoof/oulu_npu-dev-spoof-{0000..0107}.tar",
          "/mnt/data/datasets/fas/skripsi_4_datasets/1_frame/oulu_npu/test/spoof/oulu_npu-test-spoof-{0000..0143}.tar",
        ]

      - dom_lbl: -1
        name: "replay_attack_live"
        url: [
          "/mnt/data/datasets/fas/skripsi_4_datasets/1_frame/replay_attack/train/live/replay_attack-train-live-{0000..0005}.tar",
          "/mnt/data/datasets/fas/skripsi_4_datasets/1_frame/replay_attack/test/live/replay_attack-test-live-{0000..0007}.tar",
        ]
      - dom_lbl: 2
        name: "replay_attack_spoof"
        url: [
          "/mnt/data/datasets/fas/skripsi_4_datasets/1_frame/replay_attack/train/spoof/replay_attack-train-spoof-{0000..0014}.tar",
          "/mnt/data/datasets/fas/skripsi_4_datasets/1_frame/replay_attack/test/spoof/replay_attack-test-spoof-{0000..0019}.tar",
        ]

      - dom_lbl: -2
        name: "msu_mfsd_live"
        url: [
          "/mnt/data/datasets/fas/skripsi_4_datasets/1_frame/msu_mfsd/train/live/msu_mfsd-train-live-{0000..0002}.tar",
          "/mnt/data/datasets/fas/skripsi_4_datasets/1_frame/msu_mfsd/test/live/msu_mfsd-test-live-{0000..0003}.tar",
        ]
      - dom_lbl: 3
        name: "msu_mfsd_spoof"
        url: [
          "/mnt/data/datasets/fas/skripsi_4_datasets/1_frame/msu_mfsd/train/spoof/msu_mfsd-train-spoof-{0000..0008}.tar",
          "/mnt/data/datasets/fas/skripsi_4_datasets/1_frame/msu_mfsd/test/spoof/msu_mfsd-test-spoof-{0000..0011}.tar",
        ]

  val_dataset:
    disable_blank_mitigation: true
    align_config:
      scale: 0.75
      crop_size: 256 
      select_method: AREA
      no_face_handling: skip
    urls:
      - name: "casia_mfsd_test"
        size: 1200
        url: [
        "/mnt/data/datasets/fas/skripsi_4_datasets/2_frame/casia_mfsd/train/live/casia_mfsd-train-live-{0000..0011}.tar",
        "/mnt/data/datasets/fas/skripsi_4_datasets/2_frame/casia_mfsd/train/spoof/casia_mfsd-train-spoof-{0000..0035}.tar",
        "/mnt/data/datasets/fas/skripsi_4_datasets/2_frame/casia_mfsd/test/live/casia_mfsd-test-live-{0000..0017}.tar",
        "/mnt/data/datasets/fas/skripsi_4_datasets/2_frame/casia_mfsd/test/spoof/casia_mfsd-test-spoof-{0000..0053}.tar",
        ]
        

  train_aug:
    transforms:
      - type: torchvision.transforms.RandomHorizontalFlip
        p: 0.5
      - type: torchvision.transforms.ToTensor
      - type: torchvision.transforms.Normalize
        mean: [0.5, 0.5, 0.5]
        std: [0.5, 0.5, 0.5]

  val_aug:
    transforms:
      - type: torchvision.transforms.ToTensor
      - type: torchvision.transforms.Normalize
        mean: [0.5, 0.5, 0.5]
        std: [0.5, 0.5, 0.5]